pipeline {
    agent any

    stages {
        stage('unit-test-backend') {
            steps {
                dir ('bugtracker-backend') {
                   sh 'go test -v ./...'
                }

            }
        }
    }
}