pipeline {
    agent any

    stages {
        stage('unit-test-backend') {
            agent {
                docker {
                    image 'golang:tip-trixie'
                    alwaysPull true // Forces Jenkins to pull the latest image from Docker Hub
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}