pipeline {
    agent any

    stages {
        stage('unit-test-backend') {
            agent {
                docker {
                    image 'golang:tip-trixie'
                    reuseNode true
                }
            }
            steps {
                dir ('bugtracker-backend') {
                   sh 'go test -v ./...'
                }

            }
        }
    }
}